nr_passes = 3

[source]
image_dir = "examples/two_frames/input"
output_dir = "examples/two_frames/output"
frames_to_use = "all"
extra_vel_dim_m = 0.01

[camera]
camera_dir = "/Users/tommieverouden/Developer/tcm-piv/examples/two_frames/input/test_P-001_20260107_173921_260107_174151_metadata.json"
calib_dir = "/Users/tommieverouden/Developer/tcm-piv/examples/two_frames/input/test_P-001_20260107_173921_260107_174151_metadata.json"
calib_spacing_mm = 1.0

[preprocessing]
downsample_factor = [4, 1, 1]
background_dir = "examples/two_frames/output/background_260110_002535.tif"
crop_roi = [0, 0, 0, 0]

[correlation]
corrs_to_sum = [40, 40, 1]
nr_windows = [[1, 1], [1, 8], [1, 16]]
window_overlap = [0.0, 0.2, 0.0]

[displacement]
nr_peaks = [10, 10, 5]
min_peak_distance = [5, 5, 5]

[postprocessing]
outlier_filter_mode = ["semicircle_rect", "semicircle_rect", "circle"]
max_velocity = [[75.0, 10.0], [75.0, 5.0], [75.0, 10.0]]
neighbourhood_size = [[41, 1, 1], [51, 1, 3], [1, 1, 3]]
neighbourhood_threshold = [1, 5, [4, 6]]
time_smoothing_lambda = [4e-07, 0.0, 0.0]
flow_direction = "x"

[visualisation]
plot_model = true
model_gender = "male"
model_mass = 70.0
model_height = 1.93
plot_global_filters = true
plot_correlations = false
plot_window_layout = [true, true, true]
plot_flow_rate = true
