nr_passes = 3

[source]
image_dir = "C:\\PIV Videos\\PIV code test\\Input"
output_dir = "C:\\PIV Videos\\PIV code test\\Output"
frames_to_use = "all"
extra_vel_dim_m = 0.01

[camera]
camera_dir = "C:\\Uni\\tcm-piv\\examples\\image_pair\\output\\camera_metadata\\test_P-001_20260107_173921_260107_174151_metadata.json"
calib_dir = "C:\\Uni\\tcm-piv\\examples\\image_pair\\output\\calibration\\calibration_image_260108_141319_metadata.json"
calib_spacing_mm = 1.0

[preprocessing]
# Deze veranderd niks behalve het afschaven van enkele seconden rekenwerk
downsample_factor = [4, 1, 1]
background_dir = "C:\\PIV Videos\\PIV code test\\Output\\background_260115_121158.tif"
crop_roi = [0, 0, 0, 0]

[correlation]
corrs_to_sum = [1, 1, 1]
nr_windows = [[1, 1], [1, 8], [1, 24]]
# This one seems best between 0.5 and 0.65
window_overlap = 0.65

[displacement]
nr_peaks = 2
min_peak_distance = 1

[postprocessing]
# Deze lijkt niks te veranderen? [1,1,1] -> [3,3,3] -> [3,1,1]
neighbourhood_size = [1, 1, 1]
outlier_filter_mode = "semicircle_rect"
# Deze aanpassen na eerst snelheden checken
max_velocity = [10, 40]
flow_direction = "y"
# Doet bijna niks, lijkt wat hoger af en toe beter te verbinden richting de randen, maar niet te hoog (10+)
neighbourhood_threshold = 5
# Deze lijkt ook niks te veranderen aan de data, behalve wat kleine piekjes?
time_smoothing_lambda = 5

[visualisation]
plot_model = false
model_gender = "male"
model_mass = 70.0
model_height = 1.93
plot_global_filters = true
plot_window_layout = true
plot_flow_rate = true
export_velocity_profiles_pdf = true
