nr_passes = 3

[source]
image_dir = "examples/image_pair/input"
output_dir = "examples/image_pair/output"
frames_to_use = "all"

[camera]
camera_dir = "/Users/tommieverouden/Developer/tcm-piv/examples/image_pair/output/camera_metadata/test_P-001_20260107_173921_260107_174151_metadata.json"
calib_dir = "/Users/tommieverouden/Developer/tcm-piv/examples/image_pair/output/calibration/calibration_image_260108_141319_metadata.json"
calib_spacing_mm = 1.0

[preprocessing]
ds_factor = [4, 1, 1]
background_dir = "none"
crop_roi = [0, 0, 0, 0]

[correlation]
n_corrs_to_sum = [1, 1, 1]
n_windows = [[1, 1],[1, 8],[1, 24]]
window_overlap = [0, 0, 0.5]

[displacement]
n_peaks = 10
min_peak_dist_px = 1

[postprocessing]
outlier_filter_mode = ["semicircle_rect"]
max_velocity_vy_vx = [[100, 20]]
nb_size_tyx = [1, 1, 1]
interp_nb_size_tyx = [1, 1, 5]
nb_threshold = 5
time_smooth_lam = 0
flow_direction = "y"
extra_vel_dim_m = 0.01

[visualisation]
plot_model = true
model_gender = "male"
model_mass = 70.0
model_height = 1.93
plot_global_filters = true
plot_correlations = true
plot_window_layout = true
plot_flow_rate = true
export_velocity_profiles_pdf = true